version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  user-management:
    build: ./user-management
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq

  email-service:
    build: ./email-service
    depends_on:
      - rabbitmq
volumes:
  mongodb_data:
